files:
    - "C:\\SomeDir\\AnotherDir"
    - "C:\\SomeDir\\AnotherDir\\SomeFile.pdf"
targetDirectory: "C:\\TargetDir"
codeDirectoryName: "Code"  
gitProjects:
    - name: "Project 1"
      url: "https://url-to-clone-yout-project.git"
      ignoredBranches: 
          - "ig1"
          - "ig2"
      gitCredentials:
          userName: "Username"
          password: "Password"